# https://raw.githubusercontent.com/haskell/stylish-haskell/main/data/stylish-haskell.yaml

steps:

  - imports:
      align: none
      long_list_align: new_line
      list_padding: 4
      separate_lists: true

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true

  - trailing_whitespace: {}

columns: 80
